timeout: 3

wallpaper: boot():/images/wallpaper.png
interface_resolution: 1600x900
term_font_scale: 1x1
term_font_spacing: 0

term_background: cc000000
term_foreground: fce8ff

/Sekura
    protocol: limine

    kernel_path: boot():/boot/kernel.elf
    module_path: boot():/rootfs/sysinit/init.elf
    module_path: boot():/rootfs/sysinit/sexo2.elf